/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "frlfbtxmxsvcndlcsoth"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybGZidHhteHN2Y25kbGNzb3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODQ2NDAsImV4cCI6MjA4NjY2MDY0MH0.Mpxsvpn3nue77ibCp5AsVs2Mlpv4G2JUb-Rs2-l9FMA"